/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controll;

import Comunicate.Server;
import DataBox.ScoreHistory;
import DataBox.CrunchData;
import DataBox.FivbControolPack;
import DataBox.LastonairPlayerName;
import DataBox.Pack;
import DataBox.Playernamedata;
import DataBox.TeamGorHino;
import base.DisplayInterface;
import display1.Display_Frame_1;
import java.awt.Color;
import javax.swing.JColorChooser;
import base.DisplayInterface;
import display1.Display_Frame_1;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.binding.Bindings;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author shayan
 */
public class FivbControll extends javax.swing.JPanel implements controllInterface {

    /**
     * Creates new form FivbControll
     */
    FivbControolPack controolPack;
    // Display_Frame_1 out[];

    ControllCommandSet controllCommandSet;

    boolean show_wl_crunch;
    int selectedControlPack;
    ScoreHistory scoreHistory;
    JTextField jtextscoreHistory1[], jtextscoreHistory2[];
    String savedatapck = "FivbControlSetting.json";
    String saveCrunchAdd = "FivCrunchAdd.json";
    String lastonAirTeams = "lastonAirTeams.json";
    boolean newsha, serverFree, scoreSetShowActive, setserviceShowActive;
    Server server;
    TeamInfo[] teamInfos;
    LastonairPlayerName lastonairteaminfo;

    public FivbControll(Server server) {
        newsha = false;
        this.server = server;
        controolPack = new FivbControolPack(server.getobjecsArrayLenght());

        controllCommandSet = new ControllCommandSet(server);

        controllCommandSet.setControolPack(controolPack);
        scoreHistory = new ScoreHistory();

        initComponents();
        updatecolorSettings();
        show_wl_crunch = false;
        updateControlpack();
//        jPanelshayan.setVisible(false);

        jComboBoxAddbot.removeAllItems();

        jComboBoxAddtop.removeAllItems();
        jtextscoreHistory1 = new JTextField[scoreHistory.getMaxhistory()];
        jtextscoreHistory2 = new JTextField[scoreHistory.getMaxhistory()];
        for (int i = 0; i < scoreHistory.getMaxhistory(); i++) {
            jtextscoreHistory1[i] = new JTextField(" ");
            jtextscoreHistory2[i] = new JTextField(" ");
            jPanel_history1.add(jtextscoreHistory1[i]);
            jPanel_history2.add(jtextscoreHistory2[i]);
        }
        teamInfos = new TeamInfo[2];
        lastonairteaminfo = new FileManipulat().loadlastonanaiteamInfo(lastonAirTeams);
        for (int i = 0; i < 2; i++) {
            teamInfos[i] = new TeamInfo(this, lastonairteaminfo, i);
        }
        jTabbedPane1.add("Host Team", teamInfos[0]);
        jTabbedPane1.add("Guest Team", teamInfos[1]);
        updateFromControlpack(new FileManipulat().loadControolPack(savedatapck, server.getobjecsArrayLenght()));
        loadCrunchData();
        newsha = true;
        serverFree = true;
        scoreSetShowActive = false;
        setserviceShowActive = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSrvs = new javax.swing.ButtonGroup();
        buttonGroupSetCounter = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jToggleButtonSHowFrame = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonColor3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonColor1 = new javax.swing.JButton();
        jTextFieldCountry_1 = new javax.swing.JTextField();
        jTextFieldSet_1 = new javax.swing.JTextField();
        jTextField_point_1 = new javax.swing.JTextField();
        jRadioButtonSrv1 = new javax.swing.JRadioButton();
        jButton_min_1 = new javax.swing.JButton();
        jButton_Plus_1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonColor2 = new javax.swing.JButton();
        jTextFieldCountry_2 = new javax.swing.JTextField();
        jTextFieldSet_2 = new javax.swing.JTextField();
        jTextField_point_2 = new javax.swing.JTextField();
        jRadioButtonSrv2 = new javax.swing.JRadioButton();
        jButton_min_2 = new javax.swing.JButton();
        jButton_Plus_2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jToggleButton_crunch_add_top = new javax.swing.JToggleButton();
        jComboBoxAddtop = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jToggleButton_crunch_add_bot = new javax.swing.JToggleButton();
        jComboBoxAddbot = new javax.swing.JComboBox();
        jPanel17 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jRadioButtoset1 = new javax.swing.JRadioButton();
        jRadioButtoset2 = new javax.swing.JRadioButton();
        jRadioButtoset3 = new javax.swing.JRadioButton();
        jRadioButtoset4 = new javax.swing.JRadioButton();
        jRadioButtoset5 = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        jTextFieldSetTop1 = new javax.swing.JTextField();
        jTextFieldSetTop2 = new javax.swing.JTextField();
        jTextFieldSetTop3 = new javax.swing.JTextField();
        jTextFieldSetTop4 = new javax.swing.JTextField();
        jTextFieldSetTop5 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jTextFieldSetbot1 = new javax.swing.JTextField();
        jTextFieldSetbot2 = new javax.swing.JTextField();
        jTextFieldSetbot3 = new javax.swing.JTextField();
        jTextFieldSetbot4 = new javax.swing.JTextField();
        jTextFieldSetbot5 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jTextFieldSetbotTimer1 = new javax.swing.JTextField();
        jTextFieldSetbotTimer2 = new javax.swing.JTextField();
        jTextFieldSetbotTimer3 = new javax.swing.JTextField();
        jTextFieldSetbotTimer4 = new javax.swing.JTextField();
        jTextFieldSetbotTimer5 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        Set = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButtoncrunch_show = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jToggleButtonPbPVertical = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButtonPlayByPlay = new javax.swing.JToggleButton();
        jPanel_history1 = new javax.swing.JPanel();
        jPanel_history2 = new javax.swing.JPanel();
        jPanelsustitution = new javax.swing.JPanel();
        jToggleButtonsubstitution = new javax.swing.JToggleButton();
        jPanelScore_set_result = new javax.swing.JPanel();
        jToggleButtonExpandContract = new javax.swing.JToggleButton();
        jToggleButtonSore_set = new javax.swing.JToggleButton();
        jToggleButtonSore_REsult = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel13.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jPanel11.setPreferredSize(new java.awt.Dimension(0, 0));

        jToggleButtonSHowFrame.setText("SHow Frame");
        jToggleButtonSHowFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSHowFrameActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButtonColor3.setBackground(new java.awt.Color(0, 0, 0));
        jButtonColor3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonColor3.setText(">");
        jPanel3.add(jButtonColor3);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Team");
        jPanel3.add(jLabel6);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("set");
        jPanel3.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Point");
        jPanel3.add(jLabel2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("srv");
        jPanel3.add(jLabel5);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("min");
        jPanel3.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("add");
        jPanel3.add(jLabel8);

        jPanel5.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButtonColor1.setText(">");
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonColor1);

        jTextFieldCountry_1.setText("IRN");
        jTextFieldCountry_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountry_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCountry_1);

        jTextFieldSet_1.setText("0");
        jTextFieldSet_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSet_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldSet_1);

        jTextField_point_1.setText("0");
        jTextField_point_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_point_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_point_1);

        buttonGroupSrvs.add(jRadioButtonSrv1);
        jRadioButtonSrv1.setSelected(true);
        jRadioButtonSrv1.setActionCommand("01");
        jRadioButtonSrv1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButtonSrv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonSrv1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonSrv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSrv1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonSrv1);

        jButton_min_1.setText("-");
        jButton_min_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_min_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_min_1);

        jButton_Plus_1.setText("+");
        jButton_Plus_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Plus_1);

        jPanel5.add(jPanel2);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButtonColor2.setText(">");
        jButtonColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonColor2);

        jTextFieldCountry_2.setText("USA");
        jTextFieldCountry_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountry_2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldCountry_2);

        jTextFieldSet_2.setText("0");
        jTextFieldSet_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSet_2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldSet_2);

        jTextField_point_2.setText("0");
        jTextField_point_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_point_2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField_point_2);

        buttonGroupSrvs.add(jRadioButtonSrv2);
        jRadioButtonSrv2.setActionCommand("02");
        jRadioButtonSrv2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButtonSrv2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonSrv2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonSrv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSrv2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonSrv2);

        jButton_min_2.setText("-");
        jButton_min_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_min_2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_min_2);

        jButton_Plus_2.setText("+");
        jButton_Plus_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plus_2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Plus_2);

        jPanel5.add(jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setMinimumSize(new java.awt.Dimension(180, 60));
        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)))
        );

        jPanel8.add(jPanel10);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jToggleButton_crunch_add_top.setText("top");
        jToggleButton_crunch_add_top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_crunch_add_topActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton_crunch_add_top);

        jComboBoxAddtop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAddtop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAddtopActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBoxAddtop);

        jPanel8.add(jPanel7);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jToggleButton_crunch_add_bot.setText("bot");
        jToggleButton_crunch_add_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_crunch_add_botActionPerformed(evt);
            }
        });
        jPanel9.add(jToggleButton_crunch_add_bot);

        jComboBoxAddbot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAddbot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAddbotActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxAddbot);

        jPanel8.add(jPanel9);

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(110, 60));
        jPanel12.setLayout(new java.awt.GridLayout(4, 1));

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroupSetCounter.add(jRadioButtoset1);
        jRadioButtoset1.setMnemonic('1');
        jRadioButtoset1.setSelected(true);
        jRadioButtoset1.setText("1");
        jPanel14.add(jRadioButtoset1);

        buttonGroupSetCounter.add(jRadioButtoset2);
        jRadioButtoset2.setMnemonic('2');
        jRadioButtoset2.setText("2");
        jRadioButtoset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoset2ActionPerformed(evt);
            }
        });
        jPanel14.add(jRadioButtoset2);

        buttonGroupSetCounter.add(jRadioButtoset3);
        jRadioButtoset3.setMnemonic('3');
        jRadioButtoset3.setText("3");
        jPanel14.add(jRadioButtoset3);

        buttonGroupSetCounter.add(jRadioButtoset4);
        jRadioButtoset4.setMnemonic('4');
        jRadioButtoset4.setText("4");
        jPanel14.add(jRadioButtoset4);

        buttonGroupSetCounter.add(jRadioButtoset5);
        jRadioButtoset5.setMnemonic('5');
        jRadioButtoset5.setText("5");
        jPanel14.add(jRadioButtoset5);

        jPanel12.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldSetTop1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetTop1.setText("10");
        jPanel15.add(jTextFieldSetTop1);

        jTextFieldSetTop2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel15.add(jTextFieldSetTop2);

        jTextFieldSetTop3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel15.add(jTextFieldSetTop3);

        jTextFieldSetTop4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetTop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetTop4ActionPerformed(evt);
            }
        });
        jPanel15.add(jTextFieldSetTop4);

        jTextFieldSetTop5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetTop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetTop5ActionPerformed(evt);
            }
        });
        jPanel15.add(jTextFieldSetTop5);

        jPanel12.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldSetbot1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbot1.setText("10");
        jPanel16.add(jTextFieldSetbot1);

        jTextFieldSetbot2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel16.add(jTextFieldSetbot2);

        jTextFieldSetbot3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel16.add(jTextFieldSetbot3);

        jTextFieldSetbot4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbot4ActionPerformed(evt);
            }
        });
        jPanel16.add(jTextFieldSetbot4);

        jTextFieldSetbot5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbot5ActionPerformed(evt);
            }
        });
        jPanel16.add(jTextFieldSetbot5);

        jPanel12.add(jPanel16);

        jPanel24.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldSetbotTimer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbotTimer1.setText("10'");
        jPanel24.add(jTextFieldSetbotTimer1);

        jTextFieldSetbotTimer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbotTimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbotTimer2ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextFieldSetbotTimer2);

        jTextFieldSetbotTimer3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbotTimer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbotTimer3ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextFieldSetbotTimer3);

        jTextFieldSetbotTimer4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbotTimer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbotTimer4ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextFieldSetbotTimer4);

        jTextFieldSetbotTimer5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSetbotTimer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSetbotTimer5ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextFieldSetbotTimer5);

        jPanel12.add(jPanel24);

        jPanel17.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(90, 60));
        jPanel18.setLayout(new java.awt.GridLayout(0, 1));

        Set.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Set.setText("SET");
        jPanel18.add(Set);

        jToggleButton1.setText("start");
        jPanel18.add(jToggleButton1);

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton5);

        jPanel17.add(jPanel18, java.awt.BorderLayout.EAST);

        jLabel3.setText("crunchScore");

        jToggleButtoncrunch_show.setText("Show");
        jToggleButtoncrunch_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtoncrunch_showActionPerformed(evt);
            }
        });

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtoncrunch_show, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jToggleButtoncrunch_show)
                .addComponent(jButton1))
        );

        jPanel21.setLayout(new java.awt.GridLayout());

        jPanel22.setLayout(new java.awt.GridLayout(0, 1));

        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jToggleButtonPbPVertical.setText("Vertical");
        jToggleButtonPbPVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPbPVerticalActionPerformed(evt);
            }
        });
        jPanel23.add(jToggleButtonPbPVertical);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Play By Play");
        jPanel23.add(jLabel4);

        jToggleButtonPlayByPlay.setText("Horizon_crunch");
        jToggleButtonPlayByPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPlayByPlayActionPerformed(evt);
            }
        });
        jPanel23.add(jToggleButtonPlayByPlay);

        jPanel22.add(jPanel23);

        jPanel_history1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_history1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel22.add(jPanel_history1);

        jPanel_history2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_history2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel22.add(jPanel_history2);

        jPanel21.add(jPanel22);

        jToggleButtonsubstitution.setText("Substitution Coach Out");
        jToggleButtonsubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsubstitutionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelsustitutionLayout = new javax.swing.GroupLayout(jPanelsustitution);
        jPanelsustitution.setLayout(jPanelsustitutionLayout);
        jPanelsustitutionLayout.setHorizontalGroup(
            jPanelsustitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsustitutionLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jToggleButtonsubstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelsustitutionLayout.setVerticalGroup(
            jPanelsustitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsustitutionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonsubstitution)
                .addContainerGap())
        );

        jToggleButtonExpandContract.setText("Expand");
        jToggleButtonExpandContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExpandContractActionPerformed(evt);
            }
        });

        jToggleButtonSore_set.setText("Set_score");
        jToggleButtonSore_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSore_setActionPerformed(evt);
            }
        });

        jToggleButtonSore_REsult.setText("Result_score");
        jToggleButtonSore_REsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSore_REsultActionPerformed(evt);
            }
        });

        jButton3.setText("reset-All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelScore_set_resultLayout = new javax.swing.GroupLayout(jPanelScore_set_result);
        jPanelScore_set_result.setLayout(jPanelScore_set_resultLayout);
        jPanelScore_set_resultLayout.setHorizontalGroup(
            jPanelScore_set_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScore_set_resultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelScore_set_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonExpandContract, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelScore_set_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonSore_REsult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSore_set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelScore_set_resultLayout.setVerticalGroup(
            jPanelScore_set_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScore_set_resultLayout.createSequentialGroup()
                .addGroup(jPanelScore_set_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonSore_set, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jToggleButtonExpandContract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelScore_set_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButtonSore_REsult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelScore_set_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelsustitution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanelsustitution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelScore_set_result, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jToggleButtonSHowFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(692, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jToggleButtonSHowFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel11);

        jTabbedPane1.addTab("MainController", jPanel13);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Plus_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_2ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_point_2.getText());
        x++;
        scoreHistory.addscores(0, x);
        updatescoreHistory();
        jTextField_point_2.setText(String.valueOf(x));
        jRadioButtonSrv2.setSelected(true);
        setserviceShowActive = true;
        updateControlpack();
        setserviceShowActive = false;
    }//GEN-LAST:event_jButton_Plus_2ActionPerformed

    private void jButton_min_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_min_2ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_point_2.getText());
        if (x > 1) {
            x--;
            scoreHistory.removescore();
            updatescoreHistory();
        }
        jTextField_point_2.setText(String.valueOf(x));
//        buttonGroupSrvs.clearSelection();
        updateControlpack();
    }//GEN-LAST:event_jButton_min_2ActionPerformed

    private void jRadioButtonSrv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSrv2ActionPerformed
        // TODO add your handling code here:
//        updateControlpack();
        setserviceShowActive = true;
        updateControlpack();
        setserviceShowActive = false;
    }//GEN-LAST:event_jRadioButtonSrv2ActionPerformed

    private void jTextField_point_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_point_2ActionPerformed
        // TODO add your handling code here:
        updateControlpack();
    }//GEN-LAST:event_jTextField_point_2ActionPerformed

    private void jTextFieldSet_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSet_2ActionPerformed
        // TODO add your handling code here:
        updateControlpack();
    }//GEN-LAST:event_jTextFieldSet_2ActionPerformed

    private void jTextFieldCountry_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountry_2ActionPerformed
        // TODO add your handling code here:
        updateControlpack();
    }//GEN-LAST:event_jTextFieldCountry_2ActionPerformed

    private void jButtonColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor2ActionPerformed
        // TODO add your handling code here:
        if (newsha) {
            Color c = JColorChooser.showDialog(null, "Choose a Color", jButtonColor2.getForeground());
            if (c != null) {
                setcolor2(c);
            }
        }
    }//GEN-LAST:event_jButtonColor2ActionPerformed

    private void jButton_Plus_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plus_1ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_point_1.getText());
        x++;
        scoreHistory.addscores(x, 0);
        updatescoreHistory();
        jTextField_point_1.setText(String.valueOf(x));
        jRadioButtonSrv1.setSelected(true);
        setserviceShowActive = true;
        updateControlpack();
        setserviceShowActive = false;

    }//GEN-LAST:event_jButton_Plus_1ActionPerformed

    private void jButton_min_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_min_1ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_point_1.getText());
        if (x > 1) {
            x--;
            scoreHistory.removescore();
            updatescoreHistory();
        }
        jTextField_point_1.setText(String.valueOf(x));
//        buttonGroupSrvs.clearSelection();
        updateControlpack();
    }//GEN-LAST:event_jButton_min_1ActionPerformed

    private void jRadioButtonSrv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSrv1ActionPerformed
        // TODO add your handling code here:
//        updateControlpack();
        setserviceShowActive = true;
        updateControlpack();
        setserviceShowActive = false;
    }//GEN-LAST:event_jRadioButtonSrv1ActionPerformed

    private void jTextField_point_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_point_1ActionPerformed
        // TODO add your handling code here:
        updateControlpack();
    }//GEN-LAST:event_jTextField_point_1ActionPerformed

    private void jTextFieldSet_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSet_1ActionPerformed
        // TODO add your handling code here:
        updateControlpack();
    }//GEN-LAST:event_jTextFieldSet_1ActionPerformed

    private void jTextFieldCountry_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountry_1ActionPerformed
        // TODO add your handling code here:
        if (newsha) {
            updateControlpack();
        }
    }//GEN-LAST:event_jTextFieldCountry_1ActionPerformed

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", jButtonColor1.getForeground());
        setcolor1(c);
    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateControlpack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButtoncrunch_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtoncrunch_showActionPerformed
        // TODO add your handling code here:
        updateControlpack();
        if (jToggleButtoncrunch_show.isSelected()) {
            jToggleButtoncrunch_show.setText("Hide");
//            jToggleButton_crunch_add_bot.setSelected(false);
//            jToggleButton_crunch_add_top.setSelected(false);
//            jToggleButtonExpandContract.setSelected(false);
//            jToggleButtonPlayByPlay.setSelected(false);
            controllCommandSet.crunchscore_show();
            setservice();

        } else {
            jToggleButtoncrunch_show.setText("Show");
            controllCommandSet.crunchscore_Hide();
        }

    }//GEN-LAST:event_jToggleButtoncrunch_showActionPerformed

    private void jToggleButtonSHowFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSHowFrameActionPerformed
        // TODO add your handling code here:
//        for (Display_Frame_1 out1 : out) {
//            out1.setVisible(jToggleButtonSHowFrame.isSelected());
//        }

        updateControlpack();
        controolPack.setFramevis(jToggleButtonSHowFrame.isSelected());
        outUpdate();
    }//GEN-LAST:event_jToggleButtonSHowFrameActionPerformed

    private void jComboBoxAddtopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAddtopActionPerformed
        // TODO add your handling code here:
        jToggleButton_crunch_add_top.setText((String) jComboBoxAddtop.getSelectedItem());
    }//GEN-LAST:event_jComboBoxAddtopActionPerformed

    private void jComboBoxAddbotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAddbotActionPerformed
        // TODO add your handling code here:
        jToggleButton_crunch_add_bot.setText((String) jComboBoxAddbot.getSelectedItem());
    }//GEN-LAST:event_jComboBoxAddbotActionPerformed

    private void jToggleButton_crunch_add_topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_crunch_add_topActionPerformed
        // TODO add your handling code here:
        updateControlPackData();
        if (jToggleButton_crunch_add_top.isSelected()) {
            controllCommandSet.crunchscore_Add_Top_Show();
        } else {
            controllCommandSet.crunchscore_Add_Top_Hide();
        }
    }//GEN-LAST:event_jToggleButton_crunch_add_topActionPerformed

    private void jToggleButton_crunch_add_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_crunch_add_botActionPerformed
        // TODO add your handling code here:
        updateControlPackData();
        if (jToggleButton_crunch_add_bot.isSelected()) {
            controllCommandSet.crunchscore_Add_Bot_Show();
        } else {
            controllCommandSet.crunchscore_Add_Bot_Hide();
        }
    }//GEN-LAST:event_jToggleButton_crunch_add_botActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String st = JOptionPane.showInputDialog("Dear Ashkan Enter new title ");
        if (!st.equals("")) {
            jComboBoxAddbot.addItem(st);
            jComboBoxAddtop.addItem(st);
            saveCrunchAdd();
//            loadCrunchDate();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int x = jComboBoxAddtop.getSelectedIndex();
        jComboBoxAddtop.removeItemAt(x);
        jComboBoxAddbot.removeItemAt(x);
        saveCrunchAdd();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldSetTop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetTop4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetTop4ActionPerformed

    private void jTextFieldSetbot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbot4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbot4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        resetSet();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jToggleButtonPlayByPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPlayByPlayActionPerformed
        // TODO add your handling code here:
        updateControlPackData();
        if (jToggleButtonPlayByPlay.isSelected()) {
            jToggleButtonPlayByPlay.setText("Hide History");
            controllCommandSet.crunch_PbP_expand();
        } else {
            jToggleButtonPlayByPlay.setText("Show History");
            controllCommandSet.crunch_PbP_contract();
        }
    }//GEN-LAST:event_jToggleButtonPlayByPlayActionPerformed

    private void jToggleButtonExpandContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExpandContractActionPerformed
        // TODO add your handling code here:
        updateControlPackData();
        if (jToggleButtonExpandContract.isSelected()) {
            jToggleButtonExpandContract.setText("Contract");
            controllCommandSet.crunch_expand();
        } else {
            jToggleButtonExpandContract.setText("Expand");
            controllCommandSet.crunch_contract();
        }
    }//GEN-LAST:event_jToggleButtonExpandContractActionPerformed

    private void jToggleButtonsubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsubstitutionActionPerformed
        // TODO add your handling code here:
        if (!jToggleButtonsubstitution.isSelected()) {
            teamInfos[0].Name_coach_sub_Off();
            teamInfos[1].Name_coach_sub_Off();

        } else {
            jToggleButtonsubstitution.setSelected(false);
//            jTabbedPane1.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jToggleButtonsubstitutionActionPerformed

    private void jTextFieldSetTop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetTop5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetTop5ActionPerformed

    private void jTextFieldSetbot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbot5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbot5ActionPerformed

    private void jRadioButtoset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoset2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtoset2ActionPerformed

    private void jTextFieldSetbotTimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbotTimer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbotTimer2ActionPerformed

    private void jTextFieldSetbotTimer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbotTimer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbotTimer3ActionPerformed

    private void jTextFieldSetbotTimer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbotTimer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbotTimer4ActionPerformed

    private void jTextFieldSetbotTimer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSetbotTimer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSetbotTimer5ActionPerformed

    private void jToggleButtonSore_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSore_setActionPerformed
        // TODO add your handling code here:
        score_set_lower();
    }//GEN-LAST:event_jToggleButtonSore_setActionPerformed

    private void jToggleButtonSore_REsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSore_REsultActionPerformed
        // TODO add your handling code here:
        score_Result_lower();
    }//GEN-LAST:event_jToggleButtonSore_REsultActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Sure") == 0) {
            resetSet();
            jRadioButtoset1.setSelected(true);
            jTextFieldSetTop1.setText(" ");
            jTextFieldSetbot1.setText(" ");
            jTextFieldSetbotTimer1.setText(" ");
            jTextFieldSetTop2.setText(" ");
            jTextFieldSetbot2.setText(" ");
            jTextFieldSetbotTimer2.setText(" ");
            jTextFieldSetTop3.setText(" ");
            jTextFieldSetbot3.setText(" ");
            jTextFieldSetbotTimer3.setText(" ");
            jTextFieldSetTop4.setText(" ");
            jTextFieldSetbot4.setText(" ");
            jTextFieldSetbotTimer4.setText(" ");
            jTextFieldSetTop5.setText(" ");
            jTextFieldSetbot5.setText(" ");
            jTextFieldSetbotTimer5.setText(" ");
            jTextFieldSet_1.setText(" ");
            jTextFieldSet_2.setText(" ");

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButtonPbPVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPbPVerticalActionPerformed
        // TODO add your handling code here:
        playByPlayvertical();
    }//GEN-LAST:event_jToggleButtonPbPVerticalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Set;
    private javax.swing.ButtonGroup buttonGroupSetCounter;
    private javax.swing.ButtonGroup buttonGroupSrvs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButton_Plus_1;
    private javax.swing.JButton jButton_Plus_2;
    private javax.swing.JButton jButton_min_1;
    private javax.swing.JButton jButton_min_2;
    private javax.swing.JComboBox jComboBoxAddbot;
    private javax.swing.JComboBox jComboBoxAddtop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelScore_set_result;
    private javax.swing.JPanel jPanel_history1;
    private javax.swing.JPanel jPanel_history2;
    private javax.swing.JPanel jPanelsustitution;
    private javax.swing.JRadioButton jRadioButtonSrv1;
    private javax.swing.JRadioButton jRadioButtonSrv2;
    private javax.swing.JRadioButton jRadioButtoset1;
    private javax.swing.JRadioButton jRadioButtoset2;
    private javax.swing.JRadioButton jRadioButtoset3;
    private javax.swing.JRadioButton jRadioButtoset4;
    private javax.swing.JRadioButton jRadioButtoset5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCountry_1;
    private javax.swing.JTextField jTextFieldCountry_2;
    private javax.swing.JTextField jTextFieldSetTop1;
    private javax.swing.JTextField jTextFieldSetTop2;
    private javax.swing.JTextField jTextFieldSetTop3;
    private javax.swing.JTextField jTextFieldSetTop4;
    private javax.swing.JTextField jTextFieldSetTop5;
    private javax.swing.JTextField jTextFieldSet_1;
    private javax.swing.JTextField jTextFieldSet_2;
    private javax.swing.JTextField jTextFieldSetbot1;
    private javax.swing.JTextField jTextFieldSetbot2;
    private javax.swing.JTextField jTextFieldSetbot3;
    private javax.swing.JTextField jTextFieldSetbot4;
    private javax.swing.JTextField jTextFieldSetbot5;
    private javax.swing.JTextField jTextFieldSetbotTimer1;
    private javax.swing.JTextField jTextFieldSetbotTimer2;
    private javax.swing.JTextField jTextFieldSetbotTimer3;
    private javax.swing.JTextField jTextFieldSetbotTimer4;
    private javax.swing.JTextField jTextFieldSetbotTimer5;
    private javax.swing.JTextField jTextField_point_1;
    private javax.swing.JTextField jTextField_point_2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonExpandContract;
    private javax.swing.JToggleButton jToggleButtonPbPVertical;
    private javax.swing.JToggleButton jToggleButtonPlayByPlay;
    private javax.swing.JToggleButton jToggleButtonSHowFrame;
    private javax.swing.JToggleButton jToggleButtonSore_REsult;
    private javax.swing.JToggleButton jToggleButtonSore_set;
    private javax.swing.JToggleButton jToggleButton_crunch_add_bot;
    private javax.swing.JToggleButton jToggleButton_crunch_add_top;
    private javax.swing.JToggleButton jToggleButtoncrunch_show;
    private javax.swing.JToggleButton jToggleButtonsubstitution;
    // End of variables declaration//GEN-END:variables

    private void updateFromControlpack(FivbControolPack controolPack) {
        newsha = false;
        setcolor1((Color) controolPack.getColro1());
        setcolor2((Color) controolPack.getColor2());
        jTextFieldCountry_1.setText(controolPack.getCountry1());
        jTextFieldCountry_2.setText(controolPack.getCountry2());
        jTextFieldSet_1.setText(controolPack.getSet1());
        jTextFieldSet_2.setText(controolPack.getSet2());
        jTextField_point_1.setText(controolPack.getPoint1());
        jTextField_point_2.setText(controolPack.getPoint2());
        jToggleButton_crunch_add_top.setText(controolPack.getCrunchAdd_top());
        jToggleButton_crunch_add_bot.setText(controolPack.getCrunchAdd_bot());

        jTextFieldSetTop1.setText(controolPack.getSetScoreTop(0));
        jTextFieldSetTop2.setText(controolPack.getSetScoreTop(1));
        jTextFieldSetTop3.setText(controolPack.getSetScoreTop(2));
        jTextFieldSetTop4.setText(controolPack.getSetScoreTop(3));
        jTextFieldSetTop5.setText(controolPack.getSetScoreTop(4));

        jTextFieldSetbot1.setText(controolPack.getSetScoreBot(0));
        jTextFieldSetbot2.setText(controolPack.getSetScoreBot(1));
        jTextFieldSetbot3.setText(controolPack.getSetScoreBot(2));
        jTextFieldSetbot4.setText(controolPack.getSetScoreBot(3));
        jTextFieldSetbot5.setText(controolPack.getSetScoreBot(4));
        jTextFieldSetbotTimer1.setText(controolPack.getSetDuration(0));
        jTextFieldSetbotTimer2.setText(controolPack.getSetDuration(1));
        jTextFieldSetbotTimer3.setText(controolPack.getSetDuration(2));
        jTextFieldSetbotTimer4.setText(controolPack.getSetDuration(3));
        jTextFieldSetbotTimer5.setText(controolPack.getSetDuration(4));

        updateSetCounterJradio(controolPack.getSet());

        newsha = true;

    }

    private void outUpdate() {
        if (serverFree) {
            serverFree = false;
            server.writeSocket(new Pack(1, controolPack));
            serverFree = true;
        }
    }

    private void resetcontrolPack() {
    }

    private void setservice() {
        int x = 0;
//        if (buttonGroupSrvs.getSelection() != null) {
        switch (buttonGroupSrvs.getSelection().getActionCommand()) {
            case "01":
                setserviceSub(1);
                break;
            case "02":
                setserviceSub(2);
                break;
        }
//        } else {
//            controolPack.setService(0);
//            controllCommandSet.servAllHide();

//        }
    }

    void setserviceSub(int x) {
        int y = controolPack.getService();
        if (y != x) {
            controllCommandSet.changeService(x);
        } else {
            controllCommandSet.repeatService(x);
        }
        controolPack.setService(x);
    }

    private void updatecolorSettings() {

    }

    private String colorIndicator(int i, Color c) {
        BufferedImage imagepicbuff = null;
        int color;
        int oon2;
        int alpha;
        String name = "";
        try {
            imagepicbuff = (BufferedImage) ImageIO.read(new File("pictures\\CRUNCH_team_indicator_png.png"));

            for (int x = 0; x < imagepicbuff.getWidth(); x++) {
                for (int y = 0; y < imagepicbuff.getHeight(); y++) {
                    alpha = imagepicbuff.getRGB(x, y);
                    color = ((c.getRGB() & 0x00ffffff) | (alpha & 0xff000000));
                    imagepicbuff.setRGB(x, y, color);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(ImagePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        name = "pictures\\indicator" + i + c.getRGB() + ".png";
        File f = new File(name);
        try {
            ImageIO.write(imagepicbuff, "PNG", f);
        } catch (IOException ex) {
            Logger.getLogger(FivbControll.class.getName()).log(Level.SEVERE, null, ex);
        }
        return name;
    }

    private void setcolor1(Color c) {
        if (c != null) {
            jButtonColor1.setForeground(c);
            String ind1 = colorIndicator(1, c);
            controolPack.setInd1(ind1);
            updateControlpack();
        }
    }

    private void setcolor2(Color c) {
        if (c != null) {
            jButtonColor2.setForeground(c);
            String ind2 = colorIndicator(1, c);
            controolPack.setInd2(ind2);
            updateControlpack();
        }
    }

    private void updateControlPackData() {
        controolPack.setFramevis(jToggleButtonSHowFrame.isSelected());
        controolPack.setColor1(jButtonColor1.getForeground());
        controolPack.setColor2(jButtonColor2.getForeground());
        controolPack.setCountry1(jTextFieldCountry_1.getText());
        controolPack.setCountry2(jTextFieldCountry_2.getText());
        controolPack.setSet1(jTextFieldSet_1.getText());
        controolPack.setSet2(jTextFieldSet_2.getText());
        controolPack.setPoint1(jTextField_point_1.getText());
        controolPack.setPoint2(jTextField_point_2.getText());
        controolPack.setCrunchAdd_top(jToggleButton_crunch_add_top.getText());
        controolPack.setCrunchAdd_bot(jToggleButton_crunch_add_bot.getText());

        controolPack.setSetScoreBot(0, jTextFieldSetbot1.getText());
        controolPack.setSetScoreBot(1, jTextFieldSetbot2.getText());
        controolPack.setSetScoreBot(2, jTextFieldSetbot3.getText());
        controolPack.setSetScoreBot(3, jTextFieldSetbot4.getText());
        controolPack.setSetScoreBot(4, jTextFieldSetbot5.getText());
        controolPack.setSetScoreTop(0, jTextFieldSetTop1.getText());
        controolPack.setSetScoreTop(1, jTextFieldSetTop2.getText());
        controolPack.setSetScoreTop(2, jTextFieldSetTop3.getText());
        controolPack.setSetScoreTop(3, jTextFieldSetTop4.getText());
        controolPack.setSetScoreTop(4, jTextFieldSetTop5.getText());
        controolPack.setSetDuration(0, jTextFieldSetbotTimer1.getText());
        controolPack.setSetDuration(1, jTextFieldSetbotTimer2.getText());
        controolPack.setSetDuration(2, jTextFieldSetbotTimer3.getText());
        controolPack.setSetDuration(3, jTextFieldSetbotTimer4.getText());
        controolPack.setSetDuration(4, jTextFieldSetbotTimer5.getText());

        if (buttonGroupSetCounter.getSelection() != null) {
            int x = ((buttonGroupSetCounter.getSelection()).getMnemonic() - 48);
            controolPack.setSet(x);
        }
        controolPack.setScoreHistory(scoreHistory);

    }

    private void updateScoreSetShowEnd() {
                controolPack.setSetScoreTop(4, jTextField_point_1.getText());
                controolPack.setSetScoreBot(4, jTextField_point_2.getText());

    }

    private void updateControlpack(Playernamedata playernamedata) {
        controolPack.setPlayernamedata(playernamedata);
    }

    public void updateControlpack() {
        if (newsha) {
            newsha = false;
            updateControlPackData();
            if (scoreSetShowActive) {
                updateScoreSetShowEnd();
            }
            if (setserviceShowActive) {
                setservice();
            }
            outUpdate();
            controolPack.setObjectanim(55, false);
            controolPack.setObjectanim(54, false);
            controolPack.setObjectanim(122, false);
            controolPack.setObjectanim(123, false);
            controolPack.setObjectanim(124, false);
            controolPack.setObjectanim(125, false);
            controolPack.setObjectanim(126, false);
            controolPack.setObjectanim(127, false);
            updateSetsPoint();
            new FileManipulat().saveObject(savedatapck, controolPack);
            newsha = true;
        }
//        outUpdate();

    }

    private void loadCrunchData() {
        jComboBoxAddbot.removeAllItems();
        jComboBoxAddtop.removeAllItems();
        CrunchData cd = (CrunchData) new FileManipulat().loadCrunchData(saveCrunchAdd);
        for (Iterator iterator = cd.getCrunch_Add_top().iterator(); iterator.hasNext();) {
            Object next = iterator.next();
            jComboBoxAddbot.addItem(next.toString());
            jComboBoxAddtop.addItem(next.toString());
        }
    }

    private void saveCrunchAdd() {
        int x = jComboBoxAddbot.getItemCount();
        CrunchData c = new CrunchData();
        for (int i = 0; i < x; i++) {
            c.addCrunch_Add_top((String) jComboBoxAddbot.getItemAt(i));
        }
        new FileManipulat().saveObject(saveCrunchAdd, c);
    }

    private void resetSet() {
        jTextField_point_1.setText("0");
        jTextField_point_2.setText("0");
        scoreHistory.reset();
        updatescoreHistory();
    }

    private void updatescoreHistory() {
        for (int i = 0; i < scoreHistory.getMaxhistory(); i++) {
            jtextscoreHistory1[i].setText(scoreHistory.getscore1(i));
            jtextscoreHistory2[i].setText(scoreHistory.getscore2(i));
        }
    }

    @Override
    public void updateelastonairteaminfo(TeamGorHino gorHino) {//int ab, String[] numberA, String[] nameA, String[] ageA, String[] heightA, String country, String countrypic) {
        if (gorHino.getAb() == 0) {
            lastonairteaminfo.setAgeA(gorHino.getAgeA());
            lastonairteaminfo.setHeighA(gorHino.getHeightA());
            lastonairteaminfo.setNamesA(gorHino.getNameA());
            lastonairteaminfo.setNumberA(gorHino.getNumberA());
            lastonairteaminfo.setCountryA(gorHino.getCountry());
            lastonairteaminfo.setCountryPicA(gorHino.getCountryPic());
            lastonairteaminfo.setCoachA(gorHino.getCoach());
        } else {
            lastonairteaminfo.setAgeB(gorHino.getAgeA());
            lastonairteaminfo.setHeighB(gorHino.getHeightA());
            lastonairteaminfo.setNamesB(gorHino.getNameA());
            lastonairteaminfo.setNumberB(gorHino.getNumberA());
            lastonairteaminfo.setCountryB(gorHino.getCountry());
            lastonairteaminfo.setCountryPicB(gorHino.getCountryPic());
            lastonairteaminfo.setCoachB(gorHino.getCoach());
        }
        lastonairteaminfo.setSubstituationIn(gorHino.getSubstituationIn());
        lastonairteaminfo.setSubstituationOut(gorHino.getSubstituationOut());
        new FileManipulat().saveObject(lastonAirTeams, lastonairteaminfo);
    }

    @Override
    public void showPlayernameOn(Playernamedata playernamedata) {
        updateControlpack(playernamedata);
        teamInfoActive();
        controllCommandSet.PlayerNameshowOn();
    }

    @Override
    public void showPlayernameOff() {
        teamInfoDeActive();
        controllCommandSet.PlayerNamesOff();
    }

    @Override
    public void showPlayerinOnlyName(Playernamedata playernamedata) {
        updateControlpack(playernamedata);
        controllCommandSet.showsubInname();
    }

    @Override
    public void showPlayerinall(Playernamedata playernamedata) {
        updateControlpack(playernamedata);
        teamInfoActive();
        controllCommandSet.showsubInAll();

    }

    @Override
    public void showPlayerOutOnlyName(Playernamedata playernamedata) {
        updateControlpack(playernamedata);
        controllCommandSet.showsubOutname();
    }

    @Override
    public void showPlayerOutall(Playernamedata playernamedata) {
        updateControlpack(playernamedata);
        teamInfoActive();
        controllCommandSet.showsubOutAll();
    }

    @Override
    public void showPlayerInOutFree() {
        teamInfoDeActive();
        controllCommandSet.showsubAllOff();
    }

    @Override
    public void showCoachOff() {
        teamInfoDeActive();
        controllCommandSet.coatchNameShowOff();
    }

    @Override
    public void showCoachOn(Playernamedata playernamedata) {
        playernamedata.setNamePlayer(playernamedata.getCoach());
          playernamedata.setNumber(" ");
           playernamedata.setCountry("HEAD COACH");
         updateControlpack(playernamedata);
        teamInfoActive();
        controllCommandSet.coatchNameShowOn();
        

    }

    private void teamInfoActive() {
        jToggleButtonsubstitution.setSelected(true);
        jPanelsustitution.setBackground(Color.red);
    }

    private void teamInfoDeActive() {
        jToggleButtonsubstitution.setSelected(false);
        jPanelsustitution.setBackground(Color.gray);
    }

    private void updateSetsPoint() {
        switch (controolPack.getSet()) {
            case 1:
                jTextFieldSetTop1.setText(controolPack.getPoint1());
                jTextFieldSetbot1.setText(controolPack.getPoint2());
                break;
            case 2:
                jTextFieldSetTop2.setText(controolPack.getPoint1());
                jTextFieldSetbot2.setText(controolPack.getPoint2());
                break;
            case 3:
                jTextFieldSetTop3.setText(controolPack.getPoint1());
                jTextFieldSetbot3.setText(controolPack.getPoint2());
                break;
            case 4:
                jTextFieldSetTop4.setText(controolPack.getPoint1());
                jTextFieldSetbot4.setText(controolPack.getPoint2());
                break;
            default:
                jTextFieldSetTop5.setText(controolPack.getPoint1());
                jTextFieldSetbot5.setText(controolPack.getPoint2());
                break;

        }
    }

    private void updateSetCounterJradio(int set) {
        switch (set) {
            case 1:
                jRadioButtoset1.setSelected(true);
                break;
            case 2:
                jRadioButtoset2.setSelected(true);
                break;
            case 3:
                jRadioButtoset3.setSelected(true);
                break;
            case 4:
                jRadioButtoset4.setSelected(true);
                break;
            default:
                jRadioButtoset5.setSelected(true);
                break;
        }
    }

    private void score_set_lower() {

        if (jToggleButtonSore_set.isSelected()) {
            jPanelScore_set_result.setBackground(Color.red);
            scoreSetShowActive = true;
            updateControlpack();
            controllCommandSet.score_Set_showOn();
        } else {
            jPanelScore_set_result.setBackground(Color.gray);
            scoreSetShowActive = false;
            updateControlpack();
            controllCommandSet.score_Set_showOff();
        }
    }

    private void score_Result_lower() {
        if (jToggleButtonSore_REsult.isSelected()) {
            jPanelScore_set_result.setBackground(Color.red);
            controllCommandSet.score_Result_showOn();
        } else {
            jPanelScore_set_result.setBackground(Color.gray);
            controllCommandSet.score_Result_showOff();
        }
    }

    private void playByPlayvertical() {
        if (jToggleButtonPbPVertical.isSelected()) {
            jPanelScore_set_result.setBackground(Color.red);
            controllCommandSet.PlayByPlayVerticalshowOn();
        } else {
            jPanelScore_set_result.setBackground(Color.gray);
            controllCommandSet.PlayByPlayVerticalshowOff();
        }
    }

}
