/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controll;

import Comunicate.Client;
import Comunicate.Server;
import display1.Display_Frame_1;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author shayan
 */
public class Fivb extends javax.swing.JFrame {

    display1.Display_Frame_1 out[];
    FivbControll controll;
    Settings settings;
       private final Server server;
Client outold[];

    /**
     * Creates new form Letter2
     */
    public Fivb() {
        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(
                    UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
//          setDefaultLookAndFeelDecorated(true);

        initComponents();
         server = new Server();
        new Thread(server).start();
        //for Clients
        outold = new Client[1];
        outold[0] = new Client(false);
        outold[0].getDisplay_Frame().setPanelName("FULL___");
    //    outold[1] = new Client(true);
    //    outold[1].getDisplay_Frame().setPanelName("preview");

        outold[0].getDisplay_Frame().setDefaultLookAndFeelDecorated(true);

        new Thread(outold[0]).start();
    //       new Thread(outold[1]).start();
//        for (int j = 0; j < 10000; j++) { 
//        for (int i = 0; i < 100000; i++) {
//           
//        }
////         System.out.print(j+" ");
//        }
        

        settings = new Settings(server);
        controll = new FivbControll(server);
        
      /**  
        out = new Display_Frame_1[2];

        out[0] = new Display_Frame_1(false);
        out[1] = new Display_Frame_1(true);
        out[1].setPreview(true);
        out[0].setPanelName("full");
        out[1].setPanelName("Pre");
//        out[1].setVisible(true);
//        System.out.println("out1 ok");
        settings = new Settings(out);
//        System.out.println("Settings ok");
        controll = new FivbControll(out);
//        System.out.println("FivbControll(out); ok");
* **/
        jTabbedPane1.add("اجرای برنامه", controll);
//        System.out.println("برنامه(out); ok");
        jTabbedPane1.add("تنظیمات", settings);
//        System.out.println("تنظیمات(out); ok");

//        out[1].setDefaultLookAndFeelDecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fivb().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
